### ISSUE TITLE
JSON deserialization

### ISSUE THREAD

**Issue by shyiko** [siddontang/go-mysql#100]
Hi. I've noticed you added JSON support. mysql-binlog-connector-java@master is missing [a number of changes](https://github.com/shyiko/mysql-binlog-connector-java/compare/0.5.0...0.5.2) that were included in 0.5.2 that you might be interested in. This one in particular (https://github.com/shyiko/mysql-binlog-connector-java/commit/881e9c785ff71a9f14ea8e44d0e6a3bc4346b535). Take a look. It might save you from a couple of bug reports. Cheers!

**Comment by shyiko** [comment]
#93

**Comment by siddontang** [comment]
Thanks @shyiko

I will look at it later :-)
