### ISSUE TITLE
gtid replication, how to tell the master our GTID_PURGED

### ISSUE THREAD

**Issue by glycerine** [siddontang/go-mysql#114]
Thanks for this nice library. It is super helpful.

I'm trying to start gtid based binlog replication, but my server is closing the connection before my (Go) slave can get started:

~~~
binlogstreamer.go:47: [error] close sync with err: ERROR 1236 (HY000): 
The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, 
but the master has purged binary logs containing GTIDs that the slave requires.
~~~

According to https://www.percona.com/blog/2013/02/08/how-to-createrestore-a-slave-using-gtid-replication-in-mysql-5-6/ I simply need to set GTID_PURGED on the (Go) slave, so that it gets communicated to the server. 

I don't see any place in the Go api of go-mysql to set the GTID_PURGED value.  Is there one? I'm not sure how the master is asking the slave; or maybe the slave is just passing along that info in some initialization message?

**Comment by glycerine** [comment]
Nevermind. The issue was the there were two (2) sets of gtids that the server needed to hear about, and I was supplying only one to syncer.StartSyncGTID(gtids)

**Comment by siddontang** [comment]
:smile:

**Comment by xtrimf** [comment]
@glycerine how did you supply multiple GTIDs to the syncer?
