### ISSUE TITLE
reading the binlog, is the gtid on the record available?

### ISSUE THREAD

**Issue by glycerine** [siddontang/go-mysql#115]
I can read from the binlog starting at a given point. I could count forward from there, but I think that gaps are allowed. So I think the records from the binlog must themselves be stamped with a GTID. But when I print out these records, I only see the old offset from non-gtid replication.

~~~
 ev.Header = &replication.EventHeader{Timestamp:0x58abc314, EventType:0x1e, ServerID:0x98352c, EventSize:0x673, LogPos:0x10081, Flags:0x0}

 ev = '=== WriteRowsEventV2 ===
Date: 2017-02-20 22:33:24
Log position: 65665
Event size: 1651
TableID: 72
Flags: 1
Column count: 58
Values:
--
...
~~~

Is the GTID hiding somewhere in the binary data, just not yet decoded?

**Comment by glycerine** [comment]
With `mysqlbinlog --hexdump` I can see that there are `SET @@SESSION.GTID_NEXT` records in the binlog, I just have to figure out how to get (or get them past my filters, which are currently allowing only UPDATE_ROWS_EVENTv2 and WRITE_ROWS_EVENTv2)
~~~
# at 12893
#170221  4:33:21 server id 9975084  end_log_pos 12941 CRC32 0xf0b319b9
# Position  Timestamp   Type   Master ID        Size      Master Pos    Flags
#     325d 11 c3 ab 58   21   2c 35 98 00   30 00 00 00   8d 32 00 00   00 00
#     3270 01 37 a6 94 64 f5 8a 11  e6 93 fb 02 42 ac 14 00 |.7..d.......B...|
#     3280 03 11 00 00 00 00 00 00  00 b9 19 b3 f0          |.............|
#   GTID [commit=yes]
SET @@SESSION.GTID_NEXT= '37a69464-f58a-11e6-93fb-0242ac140003:17'/*!*/;
# at 12941
~~~

**Comment by glycerine** [comment]
Ah... It looks like the `GTID_EVENT` is a separate event that occurs before the event that it labels.

**Comment by glycerine** [comment]
So the sequence of the binlog leading up to a RowsEvent for my data, seems to be:
~~~
GTIDEvent,  which says SET @@SESSION.GTID_NEXT= 'uuid:57'/*!*/;
QueryEvent
TableMapEvent
RowsEvent
~~~

It's all there. The gtid just comes before the rows-event as a distinct and separate event, 3 events prior to the rows that it applies to.

**Comment by siddontang** [comment]
👍
