### ISSUE TITLE
Add Mysql string type in schema

### ISSUE THREAD

**Issue by arduanov** [siddontang/go-mysql#116]
Please add string schema type
I  mean

```ta.Columns[index].MysqlType = columnType```

in https://github.com/siddontang/go-mysql/blob/master/schema/schema.go#L59

**Comment by siddontang** [comment]
Hi @arduanov 

Why do you want this? If needed, could you send me a PR? 

Btw, I prefer `RawType` or `DescType` :-)

**Comment by arduanov** [comment]
Now I have only a digital columns type on the basis of which it is impossible to determine the source type Mysql columns

I need it for integration with other databases, specifically for the Apache Spark

I make PR soon, thanks
