### ISSUE TITLE
Canal.Start() not waiting for goroutines (exits early)

### ISSUE THREAD

**Issue by jbielick** [siddontang/go-mysql#120]
I have been really excited to use this library and learn from it; I've also enjoyed your posts about mysql replication in-depth. I'm a little new to Golang, so I hope this isn't a obvious question. I've had some trouble getting my application to run correctly and stay running. 

Using some code similar to the example you provided in the Readme, my go process exits very shortly after startup (prematurely) and does not continue running. It took me a while to narrow it down, but it seems like the main go process is not waiting for the `tryDump` and `startSyncBinlog` goroutines to finish. When starting my app, I can see an attempt to dump the database and parse it, but the pipe closes and the program exits before it is complete. 

I have a small script where the `#main` looks like this:

```go
func main() {

	cfg := canal.NewDefaultConfig()

	cfg.Addr = fmt.Sprintf("%s:3306", os.Getenv("MYSQL_HOST"))
	cfg.User = os.Getenv("MYSQL_USER")
	cfg.Password = os.Getenv("MYSQL_PASSWORD")
	cfg.DataDir = "./var"
	cfg.Dump.Databases = []string{os.Getenv("MYSQL_DATABASE")}
	cfg.Dump.DiscardErr = false

	c, err := canal.NewCanal(cfg)

	if err != nil {
		log.Fatal(err)
	}

	// Register a handler to handle RowsEvent
	c.RegRowsEventHandler(&rowEventHandler{})

	// Start canal
	if serr := c.Start(); serr != nil {
		log.Fatal(serr)
	}
}
```

In `canal.go` I see this function:

```go
func (c *Canal) Start() error {
	c.wg.Add(1)
	go c.run()

        // add the line below allows the app to work correctly
	// c.wg.Wait() 

	return nil
}
```

But the wait group does not wait for all of the goroutines to finish, only one of them. If I add a `c.wg.Wait()`, it waits and lets the binlog sync start and remain connected. 

Should I be invoking `c.Start()` differently? How should the process continue to stay running without adding `c.wg.Wait()`?

**Comment by siddontang** [comment]
Hi @jbielick 

I think https://github.com/siddontang/go-mysql/blob/master/cmd/go-canal/main.go#L70 can help you.

What I want here is to run canal separately and user can control when to close it outside, you can use other channel to block your main process and let canal run.

**Comment by jbielick** [comment]
Ah, a signal handler would be perfect as well. Thank you for the example; I believe I understand now!
