### ISSUE TITLE
Do not expose password in the logs

### ISSUE THREAD

**Issue by efirs** [siddontang/go-mysql#122]
Currently full connection information is printed to the logs on start.
It would be good to remove password from that output.

**Comment by siddontang** [comment]
can you send me a PR to fix it, thank you.

**Comment by b13f** [comment]
@siddontang will you approve PR with SetLogLevel in replication package?

**Comment by siddontang** [comment]
Hi @b13f 

I think users should set log level in their applications, not in the library.

**Comment by b13f** [comment]
@siddontang if I use another log package than ngaut/log I must import ngaut/log just to set log level for go-mysql. This is some package encapsulation break to set log level like that IMHO

**Comment by siddontang** [comment]
@b13f you can add a log level config for replication.
