### ISSUE TITLE
can go-mysql add the support of json fields analyze in binlog 

### ISSUE THREAD

**Issue by WangXiangUSTC** [siddontang/go-mysql#138]
I use go-mysql sync mysql data into mongodb,  It looks like it dosen't support analyze json field in binlog. For example, I insert a json value :
"info" : "{\"name\": \"abc\"}"
and will get :
"info" : BinData(0,"eyJuYW1lIjoid3gifQ==")

**Comment by siddontang** [comment]
@WangXiangUSTC 
We have already supported JSON parser.

**Comment by WangXiangUSTC** [comment]
OK, It  works well @siddontang
