### ISSUE TITLE
Why remove the function of the canal to save the master.info

### ISSUE THREAD

**Issue by anoty** [siddontang/go-mysql#158]
I think this feature is very useful, why do you want to remove？

**Comment by siddontang** [comment]
Let outer do itself. So outer can save to a file, or to etcd, or others.

**Comment by anoty** [comment]
Due to the canal to update postion is updated in real time, others if directly save postion, may save the wrong postion, such as possible to save a transaction in the middle of the position, so to restart the canal again, will fail

**Comment by siddontang** [comment]
Waiting for your PR. :-)

Btw, user can only save the position in OnRotate, OnDDL and OnXID now, maybe we should add a comment in the EventHandler interface.

**Comment by anoty** [comment]
[Done](https://github.com/siddontang/go-mysql/pull/159)

**Comment by anoty** [comment]
[This issue pr is ok](https://github.com/siddontang/go-mysql/pull/159)

**Comment by anoty** [comment]
#159
