### ISSUE TITLE
binlog解析出错

### ISSUE THREAD

**Issue by zhanglei** [siddontang/go-mysql#175]
![image](https://user-images.githubusercontent.com/241508/31928602-57f79480-b85e-11e7-89a0-44e563cad4be.png)
![image](https://user-images.githubusercontent.com/241508/31928615-64a4a89e-b85e-11e7-8f8b-5d2c9e124644.png)

**Comment by siddontang** [comment]
能否提供下表结构，以及报错日志里面对应的记录？你可以直接发邮件 

siddontang@gmail.com 给我

**Comment by zhanglei** [comment]
已发邮件
