### ISSUE TITLE
filter for canal

### ISSUE THREAD

**Issue by shabicheng** [siddontang/go-mysql#187]
In canal, only mysql dumper have a filter, but canal can't include or exclude specific tables.
Do you have a plan for this? @siddontang
Just like alibaba/canal's config canal.instance.filter.regex
Thanks.

**Comment by shabicheng** [comment]
I add include/exclude logic in my handler, but I think it will better that canal support it. 
1. canal account may have no authority to select the tables that I don't care, so there will be many errors that I don't care.
2. Skipping parsing ignored tables's row event will have better performance, especially when there are much more ignored tables's row event than wanted tables's

**Comment by siddontang** [comment]
yes, it is acceptable, can you help me add this feature?

You can check this when getting table meta and return an error to skip the events.

**Comment by shabicheng** [comment]
OK, I will move my project's include/exclude logic to canal and send a PR to you.
Thanks.

**Comment by shabicheng** [comment]
#188 add this feature, thanks @siddontang
