### ISSUE TITLE
github.com/sirupsen/logrus很耗性能

### ISSUE THREAD

**Issue by jilieryuyi** [siddontang/go-mysql#189]
github.com/sirupsen/logrus确实是非常好用，但是测试下来，发现这个东西特别的耗性能，建议生产环境将其禁用~

**Comment by siddontang** [comment]
能否提供下 benchmark 程序

**Comment by jilieryuyi** [comment]
使用github.com/sirupsen/logrus在OnRow回调中进行debug打印，测试数据大概在千万级别，如下pprof的对比结果。使用logrus，峰值内存在1.5G左右，不使用在800M左右，测试环境为mac，内存8G。

注意高亮部分的对比。82%，49% ： 45%，25%。

Showing top 20 nodes out of 58 (cum >= 15339.46MB)
      flat  flat%   sum%        cum   cum%
         0     0%     0% 84782.70MB   100%  runtime.goexit
         0     0%     0% 70306.94MB 82.93%  github.com/siddontang/go-mysql/canal.(*Canal).Run
         0     0%     0% 70306.94MB 82.93%  github.com/siddontang/go-mysql/canal.(*Canal).RunFrom
         0     0%     0% 70306.94MB 82.93%  github.com/siddontang/go-mysql/canal.(*Canal).run
         0     0%     0% 70306.94MB 82.93%  github.com/siddontang/go-mysql/canal.(*Canal).runSyncBinlog
         0     0%     0% 70306.94MB 82.93%  library.(*Binlog).Start.func2
       7MB 0.0083% 0.0083% 70306.44MB 82.93%  github.com/siddontang/go-mysql/canal.(*Canal).handleRowsEvent
         **0     0% 0.0083% 70289.94MB 82.91%  library.(*binlogHandler).OnRow
         0     0% 0.0083% 41764.22MB 49.26%  github.com/sirupsen/logrus.(*Logger).Println**
         0     0% 0.0083% 41764.22MB 49.26%  github.com/sirupsen/logrus.Println
         0     0% 0.0083% 41762.72MB 49.26%  github.com/sirupsen/logrus.(*Entry).Infoln
         0     0% 0.0083% 41762.72MB 49.26%  github.com/sirupsen/logrus.(*Entry).Println
         0     0% 0.0083% 32765.33MB 38.65%  fmt.Sprintln
         0     0% 0.0083% 32765.33MB 38.65%  github.com/sirupsen/logrus.(*Entry).sprintlnn
         0     0% 0.0083% 27884.73MB 32.89%  fmt.(*pp).printArg
   17.67MB 0.021% 0.029% 27882.20MB 32.89%  fmt.(*pp).printValue
         0     0% 0.029% 26939.05MB 31.77%  fmt.(*pp).doPrintln
 8613.24MB 10.16% 10.19% 21096.95MB 24.88%  reflect.Value.MapKeys
20300.57MB 23.94% 34.13% 20300.57MB 23.94%  runtime.mapassign
15339.46MB 18.09% 52.23% 15339.46MB 18.09%  runtime.rawstringtmp 

flat  flat%   sum%        cum   cum%
         0     0%     0%  3217.77MB   100%  runtime.goexit
         0     0%     0%  1747.62MB 54.31%  github.com/siddontang/go-mysql/replication.(*BinlogSyncer).onStream
         0     0%     0%  1468.76MB 45.65%  github.com/siddontang/go-mysql/canal.(*Canal).Run
         0     0%     0%  1468.76MB 45.65%  github.com/siddontang/go-mysql/canal.(*Canal).RunFrom
    0.50MB 0.016% 0.016%  1468.76MB 45.65%  github.com/siddontang/go-mysql/canal.(*Canal).handleRowsEvent
         0     0% 0.016%  1468.76MB 45.65%  github.com/siddontang/go-mysql/canal.(*Canal).run
         0     0% 0.016%  1468.76MB 45.65%  github.com/siddontang/go-mysql/canal.(*Canal).runSyncBinlog
         0     0% 0.016%  1468.76MB 45.65%  library.(*Binlog).Start.func2
         **0     0% 0.016%  1468.26MB 45.63%  library.(*binlogHandler).OnRow
         0     0% 0.016%  1359.48MB 42.25%  github.com/siddontang/go-mysql/replication.(*BinlogParser).Parse**
         0     0% 0.016%  1359.48MB 42.25%  github.com/siddontang/go-mysql/replication.(*BinlogSyncer).parseEvent
         0     0% 0.016%  1357.98MB 42.20%  github.com/siddontang/go-mysql/replication.(*BinlogParser).parseEvent
         0     0% 0.016%  1354.98MB 42.11%  github.com/siddontang/go-mysql/replication.(*RowsEvent).Decode
  737.94MB 22.93% 22.95%  1354.98MB 42.11%  github.com/siddontang/go-mysql/replication.(*RowsEvent).decodeRows
         0     0% 22.95%   834.12MB 25.92%  fmt.Sprintln
         **0     0% 22.95%   834.12MB 25.92%  log.Println**
         0     0% 22.95%   669.55MB 20.81%  fmt.(*pp).doPrintln
         0     0% 22.95%   669.55MB 20.81%  fmt.(*pp).printArg
         0     0% 22.95%   669.55MB 20.81%  fmt.(*pp).printValue
         0     0% 22.95%   617.04MB 19.18%  github.com/siddontang/go-mysql/replication.(*RowsEvent).decodeValue

**Comment by jilieryuyi** [comment]
项目地址：https://github.com/jilieryuyi/wing-binlog-go/blob/master/src/library/binlog.go

**Comment by siddontang** [comment]
额，不建议在生产环境用 debug mode ，通常 info 或者 error 级别，这个开销不会特别大。而且最大的开销看起来在 fmt 这个库上面。

**Comment by jilieryuyi** [comment]
谢谢，我发现了， 一部分是对比的测试数据体量不够，后续继续关注~~
