### ISSUE TITLE
BinlogSyncer.Close() will be blocked if BinlogStreamer exists

### ISSUE THREAD

**Issue by andwxh** [siddontang/go-mysql#19]
BinlogSyncer.**wg** will be **Add(1)** when creating BinlogStreamer. And BinlogSyncer.**wg** only will be decrease when an error comes to BinlogSyncer.**onStream**.
BinlogSyncer.**Close()** was waiting on **wg**.
So if I call BinlogSyncer.**Close()** when there is no error in BinlogSyncer.**onStream**, process will be blocked.

**Comment by siddontang** [comment]
The code in close sets a 100ms timeout here
```
if b.c != nil {
		b.c.SetReadDeadline(time.Now().Add(100 * time.Millisecond))
	}
```
how about using b.c.Close() directly?

**Comment by andwxh** [comment]
```
        if b.c != nil {
                b.c.SetReadDeadline(time.Now().Add(100 * time.Millisecond))
        }
        b.c.Close()
```
I tried to add b.c.Close() here.
After adding this line, the process exit successfully.

**Comment by siddontang** [comment]
Em, SetReadDeadline will have no effect if reading some data in 100ms and then be cleared. Maybe Close is right here. 
can you send me a PR to fix this?

**Comment by andwxh** [comment]
Sure, but I found another problem when verifying the fix code.
Even if I called **b.c.Close()** here, there is still a case that blocking on **b.wg.Wait()**.
Because BinlogSyncer.**parseEvent** is sending BinlogEvent to a buffered channel(s.ch), so **onStream** method may be blocking on it.

**Comment by siddontang** [comment]
How about SetReadDeadline(0)?

**Comment by andwxh** [comment]
The point is BinlogSyncer.**parseEvent** thread may be already blocked on **s.ch** before BinlogSyncer.**Close()** was called.
As long as BinlogSyncer.**Close()** waiting on **b.wg.Wait()**, no matter how to close the TCP connection, **onStream** method on the other thread will not decrease the WaitGroup.

**Comment by siddontang** [comment]
@andwxh , can above PR fix this problem?

**Comment by andwxh** [comment]
Yeah! This time its completely fixed. Thank you.

**Comment by andwxh** [comment]
I wondered is it a good practice to use two variables (**wg** & **stopCh**) in **Close()**, in order to ensure **onStream** thread stopped. But it works now.
