### ISSUE TITLE
canal set tabledb and tables not effect

### ISSUE THREAD

**Issue by Jasonzz-he** [siddontang/go-mysql#191]
cfg.Dump.TableDB = "mydb"
cfg.Dump.Tables = []string{"table1", "table2"}

when i set this but not effect 
func (h *MyEventHandler) OnRow(e *canal.RowsEvent) error {
	log.Info(e.String())
	return nil
}

print result is all table msg

--------------------------------
i see this readme have canal.start() but this not this function only ont canal.run()

**Comment by NearTan** [comment]
```
cfg.Dump.TableDB = "mydb"
cfg.Dump.Tables = []string{"table1", "table2"}
```
`TableDB` and `Tables` are just `Dump` parameters, it works on dumping binlog before canal starts. See [here](https://github.com/siddontang/go-mysql/blob/master/dump/dump.go#L149-L162)

To filter database or table, maybe this [PR](https://github.com/siddontang/go-mysql/pull/188) can help you.

**Comment by Jasonzz-he** [comment]
i got it, thanks
