### ISSUE TITLE
hava a function is canal.Rows to struct ?

### ISSUE THREAD

**Issue by Jasonzz-he** [siddontang/go-mysql#192]
when listen OnRow function: this have a param (e *canal.Rowevent) 

for example : i have a struct People , have a function param is e.Rows and been People  to the rows value to people been ?

**Comment by NearTan** [comment]
>  i have a struct People , have a function param is e.Rows and been People to the rows value to people been ?

Do you mean how to fetch data from `e.Rows` to build struct `People`?

**Comment by Jasonzz-he** [comment]
yes, there have a function ?

**Comment by NearTan** [comment]
@Jasonzz-he `OnRow` is one of `EventHandler` interface, you can implement your own logic to build struct in `OnRow` implement function like [this](https://github.com/siddontang/go-mysql/blob/master/cmd/go-canal/main.go#L107-L111).

**Comment by Jasonzz-he** [comment]
thanks
