### ISSUE TITLE
get table meta error if columnType is enum but have "int" in enum values

### ISSUE THREAD

**Issue by shabicheng** [siddontang/go-mysql#196]
For example:
`enum('appointing','serving','abnormal','stop','noaftermarket','finish','financial_audit') `

Table.AddColumn Result:
`{status 1 utf8_general_ci enum('appointing','serving','abnormal','stop','noaftermarket','finish','financial_audit') false false [] []}`

So, we should not judge `strings.Contains(columnType, "int")` first,  I wonder will it be OK if we move TYPE_NUMBER to the last `else if` statement ?

**Comment by siddontang** [comment]
@shabicheng  seem fine, can you send a PR to fix this?

**Comment by shabicheng** [comment]
fixed in #197
