### ISSUE TITLE
UNSIGNED类型字段解析错误

### ISSUE THREAD

**Issue by jilieryuyi** [siddontang/go-mysql#198]
测试用例
CREATE TABLE bar
(
   id INT        UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   dt_bit        BIT,
   dt_int8       TINYINT,
   dt_uint8      TINYINT UNSIGNED,
   dt_int16      SMALLINT,
   dt_uint16     SMALLINT UNSIGNED,
   dt_int24      MEDIUMINT,
   dt_uint24     MEDIUMINT UNSIGNED,
   dt_int32      INT,
   dt_uint32     INT UNSIGNED,
   dt_int64      BIGINT,
   dt_uint64     BIGINT UNSIGNED,
   dt_decimal    DECIMAL(38,0),
   dt_udecimal   DECIMAL(38,0) UNSIGNED,
   dt_dec        DEC(38,1),
   dt_udec       DEC(38,1) UNSIGNED,
   dt_numeric    NUMERIC(38,2),
   dt_unumeric   NUMERIC(38,2) UNSIGNED,
   dt_fixed      FIXED(38,3),
   dt_ufixed     FIXED(38,3) UNSIGNED,
   dt_float      FLOAT(38,4),
   dt_ufloat     FLOAT(38,4) UNSIGNED,
   dt_doubld     DOUBLE(38,5),
   dt_udoubld    DOUBLE(38,5) UNSIGNED,
   dt_real       REAL(38,6),
   dt_ureal      REAL(38,6) UNSIGNED,
   dt_bool       BOOL,
   dt_boolean    BOOLEAN,
   dt_date       DATE,
   dt_datetime   DATETIME,
   dt_timestamp  TIMESTAMP,
   dt_time       TIME,
   dt_year       YEAR,
   dt_tinyblob   TINYBLOB,
   dt_blob       BLOB,
   dt_mediumblob MEDIUMBLOB,
   dt_longblob   LONGBLOB,
   dt_char       CHAR(1),
   dt_varchar    VARCHAR(1),
   dt_enum       ENUM('F', 'M'),
   dt_binary     BINARY(16),
   dt_varbinary  VARBINARY(16),
   dt_set        SET('F', 'M'),
   dt_tinytext   TINYTEXT,
   dt_mediumtext MEDIUMTEXT,
   dt_text       TEXT,
   dt_longtext   LONGTEXT
);

INSERT INTO bar VALUES (NULL, 1, -128, 255, -32768, 65535, -8388608, 16777215, -2147483648, 4294967295, -9223372036854775808, 18446744073709551615, -38.0, 38.0, -38.1, 38.1, -38.2, 38.2, -38.3, 38.3, -38.4, 38.4, -38.5, 38.5, -38.6, 38.6, 1, 0, '2017-12-05', '2017-12-05 14:28:33', CURRENT_TIMESTAMP(), '14:29:22', 2017, 0x00, 0x01, 0x02, 0x03, 'C', 'V', 'F', 0x04, 0x05, 'M', 'TINYTEXT', 'MEDIUMTEXT', 'TEXT', 'LONGTEXT');

数据库mariadb
其中字段dt_uint8      TINYINT UNSIGNED 对应值为255，解析得到的值为-1，越界错误！
SMALLINT UNSIGNED,MEDIUMINT UNSIGNED, INT UNSIGNED,BIGINT UNSIGNED,等等字段同样类型的错误。

**Comment by siddontang** [comment]
mysql binlog event 没有  unsigned，所以得到的任何值都只能用 int，你需要根据你自己的实际的 table schema 去转换得到正确的值

**Comment by jilieryuyi** [comment]
明白了，谢谢
