### ISSUE TITLE
expose query info on rows event

### ISSUE THREAD

**Issue by cludden** [siddontang/go-mysql#201]
Is it possible to expose the query event leading up to a rows event? the current canal implementation filters out all query events that are not table rename query events.. would it be possible to expose all query events and let the handler decide which events to filter out?

**Comment by siddontang** [comment]
the only query event we need to handle is DDL and now we just handle rename table. I will consider handling other DDL later but not now (I have no time sadly).

What is the purpose to expose this? Can you give me some examples? Or you can send me a PR if possible.

**Comment by cludden** [comment]
I misunderstood the query event. I would like timestamp info for rows event.. is my only option to expose the `replication.EventHeader` on the canal row events ?

**Comment by siddontang** [comment]
seem yes, but why do you want to know the timestamp of the row events? Seem you can add a OnEvent handler that called for every event.
