### ISSUE TITLE
Can I implement go-mysql-bigquery using go-mysql

### ISSUE THREAD

**Issue by letusfly85** [siddontang/go-mysql#213]
@siddontang 

If you don't mind, I want to impl below. If you mind, I will delete below.

https://github.com/letusfly85/go-mysql-bigquery

Please let me know.

**Comment by siddontang** [comment]
sorry, but I see nothing in your repo, can you tell me what do you want to do?

**Comment by letusfly85** [comment]
Thank you for replying.

I want to collect data from MySQL BinLog and put them to BigQuery.
And if you don't mind, I wan to use your go-mysql library to impl it.

**Comment by siddontang** [comment]
Of course, you can. My go-mysql uses MIT license, you can use it freely.

**Comment by letusfly85** [comment]
Thank you! 😄 

I'll impl! 💪
