### ISSUE TITLE
dump.Parse method have a bug

### ISSUE THREAD

**Issue by Jasonzz-he** [siddontang/go-mysql#215]
for {
		line, err := rb.ReadString('\n')
		fmt.Println(line)
		if err != nil && err != io.EOF {
			return errors.Trace(err)
		} else if mysql.ErrorEqual(err, io.EOF) {
			break
		}

		line = line[0 : len(line)-1]

this read "\n" end and the line remove last one "\n"
someone have "\r\n" end 
so regexp “;” end not match

**Comment by siddontang** [comment]
@Jasonzz-he 

Do you run it on Windows?

**Comment by Jasonzz-he** [comment]
yes, i run it on Windows.

**Comment by siddontang** [comment]
https://github.com/siddontang/go-mysql/pull/121 handles this problem but it can't pass the CI test. Can you help me re-fix again?

**Comment by Jasonzz-he** [comment]
@siddontang 
I have fix, please handle
