### ISSUE TITLE
dump.Dump method have error 

### ISSUE THREAD

**Issue by Jasonzz-he** [siddontang/go-mysql#217]
@siddontang 

the file dump.go method Dump(w io.Write) error 
add mysqldump param error
if d.maxAllowedPacket > 0 {
		args = append(args, fmt.Sprintf("--max_allowed_packet=%dM", d.maxAllowedPacket))
	}

the --max_allowed_packet  should be --max-allowed-packet

**Comment by siddontang** [comment]
thanks @Jasonzz-he 

Can you send me a PR?

**Comment by Jasonzz-he** [comment]
@siddontang 
sorry, i have first pr on github, i don`t know send 2 pr at once， so i will one by one pr
