### ISSUE TITLE
Could not authenticate from Oracle's C# Connector to MySQL Server 

### ISSUE THREAD

**Issue by cheziyi** [siddontang/go-mysql#223]
When creating a C# project using Oracle's C# connector (version 6.7.9 to 6.10.5), it was able to connect to this MySQL server, but fails during authentication, with an exception below thrown:

`System.FormatException
  HResult=0x80131537
  Message=Input string was not in a correct format.
  Source=mscorlib
  StackTrace:
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at MySql.Data.Common.DBVersion.Parse(String versionString)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\calvin\Desktop\ConsoleApp1\ConsoleApp1\Program.cs:line 27`

I suspect it is the version number that this server tries to return that cannot be parse as an int.

**Comment by siddontang** [comment]
sorry, you said you use a C# connector connecting MySQL server, is it related to this project here?

**Comment by cheziyi** [comment]
Sorry, yes, I meant the MySQL server from this project.

**Comment by siddontang** [comment]
em, can you give me more information, I don't know what is the problem here, and sorry that I don't know C# too.

**Comment by cheziyi** [comment]
A sample C# snippet using Oracle's .NET connector will look like this:
`using System;
using MySql.Data.MySqlClient;

public class Example
{

    static void Main()
    {
        string cs = @"server=localhost;userid=user12;
            password=34klq*;database=mydb";

        MySqlConnection conn = null;

        try
        {
            conn = new MySqlConnection(cs);
            conn.Open();
            var sqcmd = new MySqlCommand("SELECT a, b from c", conn);
            sqcmd.ExecuteReader();
        }
        catch (MySqlException ex)
        {
            Console.WriteLine("Error: {0}", ex.ToString());

        }
        finally
        {
            if (conn != null)
            {
                conn.Close();
            }
        }
    }
}`

The error happens at 'conn.Open();', which will throw the exception shown above.

On the Go server, a sample implementation is as follows:
`func (h *sqlServerHandler) onAccept() {
	for {
		conn, err := h.l.Accept()
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println("Client connected.")
		go h.onConn(conn)
	}
}


func (h *sqlServerHandler) onConn(conn net.Conn) {

	var err error

	if err != nil {
		fmt.Println(err)
		return
	}

	co, err := server.NewConn(conn, h.user, h.pw, hh)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println("Client authenticated.")

	for {
		err = co.HandleCommand()
		if err != nil {
			fmt.Println(err)
			return
		}
	}
}` 

Accepting of the connection did not have any issue, but the connection is abruptly closed by the C# client on `server.NewConn()` because of the suspected issue with the server version number.

**Comment by siddontang** [comment]
The auth code is here https://github.com/siddontang/go-mysql/blob/master/server/auth.go

But I guess this error happens on the client side, maybe go-mysql returns something the C# client can't handle.

**Comment by cheziyi** [comment]
Hi, i have confirmed that it is the format of the server version string that is causing the issue. The .NET connector expects a valid MySQL version, such as `5.7.20`, instead of `go-mysql-0.1`. Would you consider providing a way to change the version string for applications using the library?

**Comment by siddontang** [comment]
of course, you can send me a PR to fix it.

**Comment by cheziyi** [comment]
Hi, PR created: https://github.com/siddontang/go-mysql/pull/225

**Comment by cheziyi** [comment]
Thanks!
