### ISSUE TITLE
Consider capture more DDL on QueryEvent

### ISSUE THREAD

**Issue by NearTan** [siddontang/go-mysql#227]
Now in QueryEvent just captures `rename`, `alter`, `drop` table clauses. 

`create` table clause is one of DDL in MySQL official definition, so it's reasonable, what do you think about that?

**Comment by NearTan** [comment]
But it may cause compatibility issues, should be consider carefully

**Comment by siddontang** [comment]
hi @NearTan 

Can you show more about the compatibility problems?

**Comment by NearTan** [comment]
@siddontang I'm not sure if someone didn't deal with the additional create table event in `onDDL` callback function

**Comment by siddontang** [comment]
@NearTan 

I think it doesn't matter. Here I guess you can want to capture the create event and get the table meta for later use. If yes, you can send me a PR.
