### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ruziyi** [siddontang/go-mysql#234]
```
package main

import (
	"fmt"
	"runtime/debug"

	"github.com/labstack/gommon/log"
	"github.com/siddontang/go-mysql/canal"
)

type MyEventHandler struct {
	canal.DummyEventHandler
}

func (h *MyEventHandler) OnRow(e *canal.RowsEvent) error {
	log.Infof("%s %v\n", e.Action, e.Rows)
	return nil
}

func (h *MyEventHandler) String() string {
	return "MyEventHandler"
}

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println(r)
			fmt.Println(string(debug.Stack()))
		}
	}()
	cfg := canal.NewDefaultConfig()
	cfg.Addr = "127.0.0.1:3306"
	cfg.User = "root"
	// We only care table canal_test in test db
	cfg.Dump.TableDB = "test"
	cfg.Dump.Tables = []string{"canal_test"}

	c, _ := canal.NewCanal(cfg)

	h := MyEventHandler{}
	// Register a handler to handle RowsEvent
	c.SetEventHandler(&h)
	// Start canal
	// c.Start()
	c.Run()
}
```

**Comment by siddontang** [comment]
can you show me the panic message? I can't run this currently.

**Comment by ruziyi** [comment]
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc04206ddf0, 0x1, 0x1)
        C:/Go/src/runtime/debug/stack.go:24 +0xae
main.main.func1()
        D:/bak/go-project/src/canal-test/main.go:28 +0x90
panic(0x631ae0, 0x7a8c80)
        C:/Go/src/runtime/panic.go:491 +0x291
canal-test/vendor/github.com/siddontang/go-mysql/canal.(*Canal).SetEventHandler(...)
        D:/bak/go-project/src/canal-test/vendor/github.com/siddontang/go-mysql/canal/handler.go:35
main.main()
        D:/bak/go-project/src/canal-test/main.go:42 +0x16a

**Comment by siddontang** [comment]
> `c, _ := canal.NewCanal(cfg)`

I guess you should check the error here

**Comment by ruziyi** [comment]
thanks
