### ISSUE TITLE
RowsEvent能不能把具体类型导出来

### ISSUE THREAD

**Issue by c-wind** [siddontang/go-mysql#237]
这个RowsEvent有办法区分具体是UPDATE,DELETE,WRITE中的哪个吗？是我没找到地方吗？
https://github.com/siddontang/go-mysql/blob/master/replication/parser.go#L297

**Comment by siddontang** [comment]
```
e.Header.EventType
```

**Comment by c-wind** [comment]
@siddontang 找到了，谢了
