### ISSUE TITLE
mysql 8.0.11 dump and sync error

### ISSUE THREAD

**Issue by haoduotnt** [siddontang/go-mysql#255]
Dump error:
----

mysql 8.0:
These deprecated compatibility SQL modes have been removed: DB2, MAXDB, MSSQL, MYSQL323, MYSQL40, ORACLE, POSTGRESQL, NO_FIELD_OPTIONS, NO_KEY_OPTIONS, NO_TABLE_OPTIONS. They can no longer be assigned to the sql_mode system variable or used as permitted values for the mysqldump --compatible option.

---

on dump need add --create-options.

---

Sync Error:

---

NFO[0000] rotate to (binlog.000002, 2624)
INFO[0000] rotate binlog to (binlog.000002, 2624)
ERRO[0029] close sync with err: EOF
ERRO[0029] canal start sync binlog err: EOF
start canal err EOF

---

```sql
table schema:
CREATE TABLE `new_table` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  `age` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

action:

INSERT INTO `test`.`new_table`
(`id`,
`name`,
`age`)
VALUES
(<{id: }>,
<{name: }>,
<{age: }>);
```

-----

I will go to the source code to try to analyze the reasons for the problem, and of course I would like to get your suggestions on this issue or my operational problems.

**Comment by siddontang** [comment]
oh, I have not tested it with MySQL 8.0...

**Comment by wenweih** [comment]
@siddontang   

> These deprecated compatibility SQL modes have been removed: DB2, MAXDB, MSSQL, MYSQL323, MYSQL40, ORACLE, POSTGRESQL, NO_FIELD_OPTIONS, NO_KEY_OPTIONS, NO_TABLE_OPTIONS. They can no longer be assigned to the sql_mode system variable or used as permitted values for the mysqldump --compatible option. 

https://bugs.mysql.com/bug.php?id=90791

**Comment by wenweih** [comment]
https://github.com/siddontang/go-mysql/issues/321
