### ISSUE TITLE
gtid mode is unusable

### ISSUE THREAD

**Issue by taylorchu** [siddontang/go-mysql#260]
There are many inconsistencies in gtid support.

For example, when gset is nil, it is unclear whether it means:
1. the client wants to use gtid or not
or
2. the client intends to use gtid, but an empty position is given so canal will start mysqldump.

As a result, there are many places where gset nullity is not checked, and causes panics.

Proposal:
1. when gtid is nil, it does not use gtid.
2. otherwise, if gtid.String() is "", it means that the client wants to use gtid but it should start mysqldump.

I want to use this issue to clarify how to represent those cases, so that I can provide a PR.

#214

**Comment by siddontang** [comment]
Hi @taylorchu 

> otherwise, if gtid.String() is "", it means that the client wants to use gtid but it should start mysqldump.

I find that https://github.com/siddontang/go-mysql/pull/261/files#diff-29b871543616f2c27c50edc9f54c566fR25 still use position even the string is empty. different from here?

**Comment by taylorchu** [comment]
I agree that part deserves more documentation because it is a special case.
After we use non-nil gtid to finish mysqldump as I described in the proposal, only the file-based position is available (from either dump output, or with a query before dump) but gtid is not. So here we continue to use file-based position to continue binlog syncer after dump.

**Comment by siddontang** [comment]
yes, that makes sense.
