### ISSUE TITLE
Extraneous parameter (or possible bug) in row_event.go decodeDecimal()

### ISSUE THREAD

**Issue by karmakaze** [siddontang/go-mysql#29]
https://github.com/siddontang/go-mysql/blob/master/replication/row_event.go#L549
Sprintf format only has one value placeholder, seems meant for `value` not `compFractional`

**Comment by siddontang** [comment]
Hi @karmakaze , this is ok, you can see https://golang.org/pkg/fmt/  for more information.

**Comment by karmakaze** [comment]
%*d right
