### ISSUE TITLE
Infinite loop issue caused by re-sync during backup process

### ISSUE THREAD

**Issue by zhaohaidao** [siddontang/go-mysql#299]
**Problem**
The backup process will fall into an infinite loop if it starts in latest mysql binlog position, plus inappropriate timeout value.

**Reproduce Steps**
1  Start backup process with latest mysql binlog position, with 2 second timeout
2 Do nothing(Do NOT operate source db which will produce new binlog event)
3 You will find that backup process falls into an infinite loop

**RootCause**
If the backup process starts from the latest position, the binlog syncer module will trigger a wait timeout (timeout is 1 second) and execute the re-sync method, which re-reads the binlog and generates FormatDescriptionEvent and RotateEvent.
```go
         // https://github.com/siddontang/go-mysql/blob/535abe8f2eba8d1edaf1fecacea288ebb3b479ad/replication/binlogsyncer.go#L593
	for {
		data, err := b.c.ReadPacket()
		if err != nil {
                          ...
			for {
				select {
				case <-b.ctx.Done():
					s.close()
					return
				case <-time.After(time.Second):
					b.retryCount++
					if err = b.retrySync(); err != nil {
						if b.cfg.MaxReconnectAttempts > 0 && b.retryCount >= b.cfg.MaxReconnectAttempts {
							log.Errorf("retry sync err: %v, exceeded max retries (%d)", err, b.cfg.MaxReconnectAttempts)
							s.closeWithError(err)
							return
						}

						log.Errorf("retry sync err: %v, wait 1s and retry again", err)
						continue
					}
				}

				break
			}
                          ...
		}
```

Since the timeout period for GetEvent in our backup process is 2 seconds, which is greater than 1 second, the FormatDescriptionEvent and the RotateEvent will be continuously monitored before the GetEvent times out.
Then, the StartBackup process will fall into infinite loop.

The more general scenario is, if the backup **takes less time than** the re-sync timeout (for example, only need to synchronize 2 WriteRowsEvents), then re-sync will execute and generate a new FormatEvent and RotateEvent before the GetEvent times out. causing the backup process to have no chance to trigger a timeout, thus falling into an infinite loop.

**Solution**
The backup timeout period is affected by the re-sync timeout period which is not exposed to users. Therefore, it is hard for users to set a suitable backup timeout period.

- Since the re-sync timeout period is not exposed, is it more appropriate to remove the timeout from the interface of the backup process?  We can guarantee that the timeout of GetEvent less than the timeout of Re-sync in the backup implementation.

- Or we can limit the maximum number of retries for re-sync for backup process.

**Comment by siddontang** [comment]
why `data, err := b.c.ReadPacket()` returns error and enter resync?

**Comment by zhaohaidao** [comment]
The loop routine log is followed. 
```
2018/07/26 07:53:31 INFO  rotate to (mysql-bin.000004, 1633)
2018/07/26 07:53:31 INFO  receive EOF packet, retry ReadPacket
2018/07/26 07:53:31 INFO  ReadFull failed. error is EOF
2018/07/26 07:53:31 ERROR  connection was bad
2018/07/26 07:53:32 INFO  begin to re-sync from (mysql-bin.000004, 1633)
```

According to my understanding, once an EOF_packet is received, syncer will continue to read packet, and then EOF error occurred. This error will lead to re-sync.   EOF_packet handler is as followed
```go
    for {
                 // https://github.com/siddontang/go-mysql/blob/master/replication/binlogsyncer.go#L650
                 ...
		case EOF_HEADER:
			// Refer http://dev.mysql.com/doc/internals/en/packet-EOF_Packet.html
			// In the MySQL client/server protocol, EOF and OK packets serve the same purpose.
			// Some users told me that they received EOF packet here, but I don't know why.
			// So we only log a message and retry ReadPacket.
			log.Info("receive EOF packet, retry ReadPacket")
			continue
                 ...
    }

```

**Comment by siddontang** [comment]
what is your configuration?

**Comment by zhaohaidao** [comment]
You mean BinLogSyncerConfig?
```go
	syncerConfig := replication.BinlogSyncerConfig{
		Flavor:    "mysql",
		Host:      mysqlConfig.Target.Host,
		Port:      uint16(mysqlConfig.Target.Port),
		User:      mysqlConfig.Target.Username,
		Password:  mysqlConfig.Target.Password,
		ParseTime: true,
	}

```

**Comment by siddontang** [comment]
what is your server ID? don't use 0.

**Comment by zhaohaidao** [comment]
The problem is solved！Thanks a lot for your help.
this issue and related pr can be closed.

```
ERROR close sync with err: ERROR 1236 (HY000): A slave with the same server_uuid/server_id as this slave has connected to the master;
```
