### ISSUE TITLE
Selects with 0 rows result in a crash

### ISSUE THREAD

**Issue by medvednikov** [siddontang/go-mysql#30]
Hi,

When I run a select that doesn't return any rows, I get a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x693de]

goroutine 12 [running]:
github.com/siddontang/go-mysql/mysql.(*Field).Dump(0x0, 0x0, 0x0, 0x0)
	/gocode/src/github.com/siddontang/go-mysql/mysql/field.go:121 +0x4e
```

**Comment by medvednikov** [comment]
I tried to fix ```(c *Conn) writeResultset```, but it's not trivial.

```r.Fields``` contains nil values ```[ <NIL> <NIL> <NIL> ]```, and then a `Dump()` is called on that.

**Comment by medvednikov** [comment]
I think I got it, can you have a look?

https://github.com/siddontang/go-mysql/pull/31/files

Thanks

**Comment by siddontang** [comment]
Thanks @medvednikov 

what's your test sql? or can you add this test like in go-mysql/client ?

**Comment by medvednikov** [comment]
Sorry, didn't make it clear that I was using the server package. I'm building a small MySQL proxy.

I had a look at server_test.go, you are always returning `[]interface{}{1, "hello world"},`, so it's not possible to test empty results.

This is one of the possible queries:

`select str, f, e from mixer_test_conn where false`

**Comment by siddontang** [comment]
Thanks, I will see it on weekend.

**Comment by siddontang** [comment]
Hi @medvednikov 
I found the problem in mysql/resultset_helper.go  BuildSimpleTextResultset, if the resultset is empty, the field can't be made correctly. 

So maybe the best way to build result fields is to retrieve these in table directly, not from return rows values. Your PR only ignores this error, but we will still get an invalid data, you can use a wireshark to test in real mysql and can see that if the rows is empty, we can still get correct fields response. 

Sorry that I don't have any time to fix or improve this. :sob:

**Comment by medvednikov** [comment]
Hi @siddontang 
Thanks for debugging this.
With my fix I get ```Empty set (0.07 sec)```, the same response a real MySQL server sends me.
I don't know the MySQL protocol well enough to see what's missing there :)
If this PR doesn't break anything, could you please approve it, since it fixes our problem, and it would be nice not to have to maintain a fork.
Thanks

**Comment by siddontang** [comment]
Hi @medvednikov 

You should use wireshark to capture the mysql protocol, and you can see it. 
Only using mysql client doesn't work.

**Comment by siddontang** [comment]
I merge this, but maybe we could find a better way later.
