### ISSUE TITLE
特定情况下Canal退出

### ISSUE THREAD

**Issue by dominicqi** [siddontang/go-mysql#310]
1.create table test1( name   varchar(20) primary key);

2.alter table test1 add column age int;

3.insert into test1 value ('a',1);
4.drop table test1;

sync.runSyncBinlog中
1 先读取到AlterTable的Binlog的话会清除掉tablecache。
2 处理Insert的binlog的时候会从本地缓存中查询表。本地缓存中不存在。会去远程mysql查找INFORMATION_SCHEMA.TABLES。如果这个时候远端MYSQL已经执行完DROP语句的话。
抛出 error schema.ErrTableNotExist. runSyncBinlog就会退出。重启后也会卡在当前的pos上。
能否忽略掉这个表不存在的error.或者提供一个跳过当前错误binlog的方法。

**Comment by siddontang** [comment]
hi @dominicqi 

skipping this error maybe make sense, seem we have already supported it, https://github.com/siddontang/go-mysql/blob/master/canal/sync.go#L85, but I am surprised that it can't work.

Can you investigate it and help me figure it out?

**Comment by siddontang** [comment]
go-mysql-elasticsearch uses Canel directly, so if Canel ignores the error, it will also ignore it. Can you help me re-check it again? if go-mysql-elasticsearch fails, seems there is something wrong we need to fix

**Comment by dominicqi** [comment]
Canal ignores  code is  https://github.com/siddontang/go-mysql/blob/master/canal/sync.go#L85   
but the error is throws here https://github.com/siddontang/go-mysql/blob/master/canal/sync.go#L153
->  https://github.com/siddontang/go-mysql-elasticsearch/blob/master/river/sync.go#L54
-> https://github.com/siddontang/go-mysql-elasticsearch/blob/master/river/river.go#L156

cause by the DropTable QueryEvent.
