### ISSUE TITLE
build for arm fails with constant 4294967295 overflows int

### ISSUE THREAD

**Issue by cludden** [siddontang/go-mysql#314]
```
failed to build for linux_arm_7: # github.com/Jeffail/benthos/vendor/github.com/siddontang/go-mysql/replication
vendor/github.com/siddontang/go-mysql/replication/json_binary.go:472:27: constant 4294967295 overflows int
```

more info [here](https://github.com/golang/go/issues/19621#issuecomment-287858122) and [here](https://stackoverflow.com/questions/16474594/how-can-i-print-out-an-constant-uint64-in-go-using-fmt)
fix proposed in #313

**Comment by siddontang** [comment]
oh ARM.

@cludden I haven't run it on ARM, can it run well?

**Comment by cludden** [comment]
@siddontang thanks for the quick response! to clarify, I believe the error would effect any 32bit target, not just arm. but to answer your question, I haven't benchmarked it yet on an arm device. I'm working on an integration with a project that supports arm as a release target, I'll let you know how it goes.

keep up the good work!

**Comment by alarbada** [comment]
So, build fails on 32bit, now for the tidb dependency. Here's my [comment](https://github.com/pingcap/tidb/issues/3227#issuecomment-2679004365), feel free to upvote if you also want to build on 32bit archs.

**Comment by alarbada** [comment]
This issue blocks go-mysql driver from building on 32bit:
https://github.com/pingcap/tidb/issues/3227

So until it is resolved we can just support 64bit (if anyone cares about 32bit, idk).
