### ISSUE TITLE
mysql 8.0.12 binlog parse error

### ISSUE THREAD

**Issue by domyway** [siddontang/go-mysql#315]
> [2018/08/29 18:16:45] [error] binlogstreamer.go:57 close sync with err: Header &replication.EventHeader{Timestamp:0x5b86728d, EventType:0x13, ServerID:0x1, EventSize:0x4a, LogPos:0x970, Flags:0x0}, Data "^\x00\x00\x00\x00\x00\x01\x00\ahuajuan\x00\thj_access\x00\a\x03\x0f\x0f\x0f\x01\x03\x11\a\xc8\x00\xfc\x03\xfc\x03\x00\x00\x01\x01\xa0\x02\x01-", Err: EOF
> [2018/08/29 18:16:45] [error] canal.go:216 canal start sync binlog err: Header &replication.EventHeader{Timestamp:0x5b86728d, EventType:0x13, ServerID:0x1, EventSize:0x4a, LogPos:0x970, Flags:0x0}, Data "^\x00\x00\x00\x00\x00\x01\x00\ahuajuan\x00\thj_access\x00\a\x03\x0f\x0f\x0f\x01\x03\x11\a\xc8\x00\xfc\x03\xfc\x03\x00\x00\x01\x01\xa0\x02\x01-", Err: EOF

[mysql-bin.000134.zip](https://github.com/siddontang/go-mysql/files/2331746/mysql-bin.000134.zip)

**Comment by wenweih** [comment]
met the same error
