### ISSUE TITLE
replication:index out of range error

### ISSUE THREAD

**Issue by iampastor** [siddontang/go-mysql#33]
在运行的过程中，对于某一binlog位置，会报index out of range 错误，之前有邮件询问过，经过分析是发现RowEvent数据中最后多了一个字节，之后看了python-replication的代码，发现在https://github.com/noplay/python-mysql-replication/blob/master/pymysqlreplication/row_event.py#L391 判断是否结束是通过 `while self.packet.read_bytes + 1 < self.event_size` 来判断的，而你的代码https://github.com/siddontang/go-mysql/blob/master/replication/row_event.go#L260 是`for pos < len(data)` 来判断是否结束，因此如果最后多了一个字节，会使得循环继续下去而报错，在改为`for pos+1 < len(data)` 之后能够顺利的解析，不知道这样是否正确，希望能够解答下。

**Comment by siddontang** [comment]
为什么会多出一个字节？正常情况这个多出来的字节应该是个bug了吧，我现在还不清楚。

**Comment by iampastor** [comment]
那为什么python的要加1呢？

**Comment by siddontang** [comment]
不知道，所以我就不清楚啥时候会多出来一个字节了。
这个多出来的字节是协议里面带上的，正常就应该被处理，你那边能确定是什么语句可以导致这个问题？

**Comment by iampastor** [comment]
从binlog信息来看就是普通的Update，并没有特别之处。
不能确定SQL语句是怎样的，因为数据不是我自己提供的，我再看一看能否手动触发这个问题。

**Comment by gdey** [comment]
If I'm understanding the original inquiry correctly (Or I should say if google translate is translating it correctly.) Then the problem most likely is in this part of the code:
https://github.com/siddontang/go-mysql/blob/master/replication/row_event.go#L266-L270
We don't check here to see that pos is still within the bound of the len(data) but we do access data using the updated pos. 

Now why the python code does a ```+1``` on the byte count read does not make sense to me either.

**Comment by siddontang** [comment]
Aha, thanks google translate, @gdey .

So how to fix it? use `for pos + 1 < len(data)` ? 
But I still think if we decode data correctly, the updated pos may be the `len(data)`, so only `for pos < len(data)` is ok. 

I think we should construct a case for this.

**Comment by gdey** [comment]
I agree with you that ```pos < len(data)``` is okay. I don't know why the python code is doing the ```pos+1```.  What I was point out was that the ```index out of range``` could be happening in the lines I pointed out. This is because we increment pos, but then don't check to see if it's still less then ```len(data)``` before using it. If it happens that the pos is greater than ```len(data)``` that would cause and index out of range panic.

**Comment by siddontang** [comment]
@gdey  I new an issue in python-mysql-replication for this, maybe @noplay can help us. :-)

**Comment by siddontang** [comment]
@iampastor 
what's your binlog row image, minimal, noblob or full? 
https://dev.mysql.com/doc/internals/en/binlog-row-image.html
