### ISSUE TITLE
[replication] overflow when parse unsigned bigint

### ISSUE THREAD

**Issue by Ryan-Git** [siddontang/go-mysql#338]
## Related code

https://github.com/siddontang/go-mysql/blob/76c059e36c620bb2e5f8471092f9d9b22920e052/replication/row_event.go#L403

for MYSQL_TYPE_LONGLONG type in binlog, ParseBinaryInt64 is used, which would overflow for large unsigned bigint.

## Example
dump output:
```
=== WriteRowsEventV2 ===
Date: 2018-11-06 19:43:23
Log position: 650729741
Event size: 2440
TableID: 1421
Flags: 1
Column count: 12
Values:
--
0:-2940035754968694274
.....
```

actual value:
id: 15506708318740857342 (bigint(20) unsigned NOT NULL)

## Comments
There must be something indicating its signed or not. I'll figure it out..

**Comment by Ryan-Git** [comment]
It seems impossible to decide whether it's signed or not just according to binlog events. Neither the type nor the meta filed in table map event contains such info. 

@siddontang Do you think leverage the `Table` struct is a reasonable choice? Which seems to have quite a few changes.

**Comment by Ryan-Git** [comment]
ok.. I find canal api already handles this. Is it better to move it down to the replication layer?

**Comment by siddontang** [comment]
@Ryan-Git 

Mysql binlog doesn't contain any Unsigned information, we have only to know it from the table schema. And for the replication layer, it only handles binlog replication, so let's handle it ourside.

**Comment by Ryan-Git** [comment]
It's reasonable to make a direct mapping between the replication api and the mysql implementation, but as a public package rather than mysql internal, personally I still prefer the replication layer to handle it.

For now I'm ok to close the issue, it might be better to consider the movement when there're more people asking for it.  Thanks.
