### ISSUE TITLE
replication's memory issue

### ISSUE THREAD

**Issue by shimron** [siddontang/go-mysql#345]
memory grows rapidly when  there are millions of binlog events to be synced

**Comment by shimron** [comment]
![](https://ws2.sinaimg.cn/large/006tNbRwly1fy1hoaxjz8j30u00u3q9l.jpg)

**Comment by shimron** [comment]
![](https://ws2.sinaimg.cn/large/006tNbRwly1fy1hqoghi3j30u00wk45d.jpg)

**Comment by siddontang** [comment]
em, how do you use the syncer? do you fetch the binlog immediately through BinlogStreamer::GetEvent?

**Comment by shimron** [comment]
using BinlogStreamer.GetEvent() to fetch the binlog, then send the event to  the buffer channel related with table name (one table with one buffer channel, buffer size is 4096 ).  Finally, invoke the callback func to process the event from channel in sync way.

**Comment by shimron** [comment]
do you think it's possible due to the event channel's buffer size is too big in BinlogStreamer?

**Comment by siddontang** [comment]
Hi @shimron 

Maybe yes, as you can see, the most memory use is from Conn ReadPackage which creates a buffer, reads data, parses it then sends to the channel. IMO, it can't hold a large memory. You can decrease the buffer size and verify it.
