### ISSUE TITLE
关于同步帐号问题

### ISSUE THREAD

**Issue by always-waiting** [siddontang/go-mysql#346]
举一个例子：
假设要同步`db_test`数据库，用`user_canal`帐号同步，对`user_canal`开设了如下权限：
```
GRANT RELOAD, SUPER, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'user_canal'@'172.22.192.44' IDENTIFIED BY PASSWORD '*5CF2A280679B37C0F006C97CED75EDE9203EBAFB'  
```
时，db_test修改没有触发同步，但是在添加了如下权限:
```
 GRANT SELECT ON `db_test`.* TO 'user_canal'@'172.22.192.44'
```
后，`db_test`的修改就会触发同步了

这个是正常情况吗？

这样一来，需要同步那个库，就需要给`user_canal`帐号开设对应库的读权限了。

这个是程序的设计还是我们用的方式不太正确呢？
@siddontang

**Comment by always-waiting** [comment]
同时我们用mariaDB是，发现对象`e`(*canal.RowsEvent类型)的`String`方法返回的信息如下：
```
[[1 <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>] [<nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> 0]]
```
这个是什么情况？
查看了一下数据库binlog的情况，发现`  wsrep_forced_binlog_format`设置为了`NONE`是否和这个配置有关系？因为是库不是我们的，所以不能随意修改这个配置，希望能得到大神的解答

@siddontang

**Comment by siddontang** [comment]
1， 第一个问题，貌似是因为同步的时候还需要从 mysql 里面读取一些信息，你看看如果不开 select 权限，log 里面应该有错误日志
2.  你这个 rows event 是 update？你的 row format 应该是 compact 啥的，这样 event 里面只有你的修改，没修改的 col 就会显示 nil

**Comment by always-waiting** [comment]
@siddontang 
1: 第一个问题我们看了一下日志，没有任何错误，日志级别是debug，修改字段的时候，handler的OnRow事件没有触发

2: 第二个问题已经找到了原因，我们的binlog_row_image设置成了MINIMAL所以是nil了

第一个问题还是有点困惑呀，有没有其他原因?

**Comment by siddontang** [comment]
@always-waiting 

没有，我这边通常是暴力的用所有权限来的，或者你看看 MySQL 是不是也是同样的情况，如果没有 select 权限也没法 work？

**Comment by always-waiting** [comment]
@siddontang 
我看了maxwell(java写的binlog同步)，也是这样的。必须有select权限才能同步对应的库
