### ISSUE TITLE
Why use cgo?

### ISSUE THREAD

**Issue by Ryan-Git** [siddontang/go-mysql#348]
we can't cross-compile recently and find cgo is introduced by https://github.com/siddontang/go-mysql/pull/312, but I can't find any ref from or to C, what is it used for?

**Comment by siddontang** [comment]
@Ryan-Git 

If you remove cgo, can we compile the code successfully?

**Comment by Ryan-Git** [comment]
@siddontang 
yes. on my mac, after removing import "C" from conn.go & resp.go, all builds pass both directly and cross compile to amd64, linux

**Comment by siddontang** [comment]
@Ryan-Git 

Can you send me a PR to remove them?

**Comment by siddontang** [comment]
@michael2008

Any reason to add "C" here?

**Comment by Ryan-Git** [comment]
> @Ryan-Git
> 
> Can you send me a PR to remove them?

Sure. I'd like to wait one or two days if @michael2008 could reply.
