### ISSUE TITLE
mysql8, uint64解析有问题

### ISSUE THREAD

**Issue by domyway** [siddontang/go-mysql#367]
Server version: 8.0.12 MySQL Community Server - GPL

```
package main

import (
	"fmt"

	"github.com/siddontang/go-mysql/client"
)

func main() {
	c, _ := client.Connect(fmt.Sprintf("%s:%d", "127.0.0.1", 3306), fmt.Sprintf("%s", "root"), fmt.Sprintf("%s", "1"), "huajuan")
	res, err := c.Execute("SELECT * FROM hj_address WHERE uid = ?", 101638015939344)
	if err != nil {
		fmt.Printf("%v err: %s", res, err.Error())

	}
	fmt.Printf("%v", res)
}

```

err输出了 EOF， 看了下uid走到ParseBinaryUint64出来的数据是26019332080472064，不是101456884987014

表结构和数据上传在附件里
[hj_address_ceshi.sql.zip](https://github.com/siddontang/go-mysql/files/2918588/hj_address_ceshi.sql.zip)

**Comment by siddontang** [comment]
@domyway 

can you update and try again?

**Comment by domyway** [comment]
@siddontang  update and work fine~~ thks
