### ISSUE TITLE
Authentication handler

### ISSUE THREAD

**Issue by erikstmartin** [siddontang/go-mysql#4]
Authentication should be exposed as a handler that way more than a single username/password combination could be supported.

**Comment by siddontang** [comment]
Hi @erikstmartin , this is a good feature, but I have only used username/password and don't know how to use other authentications :smile: , at the same time, I ask many other Chinese company programmers, they also use username/password only, 

mysql-proxy, atlas, cobar or other proxies may also use username/password only too.

I think supporting others is not a hard thing, but now I focus on MySQL/Redis failover, Elasticsearch and have no time to do it. sorry. 

Btw, is this feature very necessary for you now?

**Comment by tylerkovacs** [comment]
Hi @siddontang. Thank you for a very useful library!

I cannot use username/password authentication at work since we enforce certificate-based authentication. Is this something you've thought about changing recently? If not, do you have any thoughts on how to extend `auth.go` to support certificates? Thank you. cc @rlowe

**Comment by siddontang** [comment]
Hi @tylerkovacs 

I have not used certificate-based authentication, can we give me some references? Then I can think how to support it.

**Comment by rlowe** [comment]
My typical approach is to register a custom tls.Config to be used with go-sql-driver sql.Open, as described at https://godoc.org/github.com/go-sql-driver/mysql#RegisterTLSConfig

**Comment by tylerkovacs** [comment]
@siddontang I've copied and tested TLS/SSL authentication support from the official Go driver. PR here:

https://github.com/siddontang/go-mysql/pull/105

cc @rlowe

**Comment by holys** [comment]
It seems that  this issue could be closed.
