### ISSUE TITLE
panic: exec: "mysqldump": executable file not found in $PATH"

### ISSUE THREAD

**Issue by gaolv123tyu** [siddontang/go-mysql#401]
what does this error "panic: exec: "mysqldump": executable file not found in $PATH" mean  , and how to deal ？

**Comment by relax-admin** [comment]
the same issue

**Comment by wule61** [comment]
> what does this error "panic: exec: "mysqldump": executable file not found in $PATH" mean , and how to deal ？

cfg.Dump.ExecutionPath = ""
