### ISSUE TITLE
Replication RowsEvent support

### ISSUE THREAD

**Issue by nholland94** [siddontang/go-mysql#41]
Hello. I have a use case where I want to read and process RowsEvents as a slave to a master MySQL DB. I had a project going that does this by tailing the binlog on the DB server itself, however, I would like to do it via the replication protocol instead. I noticed, in playing around with the replication package in the repository, that RowsEvents are just deserialized as GenericEvents. It only works with one version of MySQL currently, but I do have this library https://github.com/Granicus/mysql-binlog-go, which is capable of deserializing RowsEvents.

I want to fork this repository and add support for RowsEvents deserialization. My question to you is this: is it preferred that I create a more generic interface for my deserialization library and integrate it as a dependency here, or would it be better to attempt to fold the deserialization logic from the library into this library?

**Comment by siddontang** [comment]
Hi @nholland94 
 go-mysql parses RowsEvent, so I don't know why you said it only with GenericEvents?

**Comment by nholland94** [comment]
@siddontang Hmmm... I think I was looking at the wrong events or something. I played around with another log this morning and am seeing the RowsEvents deserialized correctly. Before, I was seeing a bunch of blank events where I was expecting RowsEvents. I must have been looking at the wrong thing or doing something wrong.

**Comment by siddontang** [comment]
:-)
