### ISSUE TITLE
关于监听指定表的问题

### ISSUE THREAD

**Issue by wule61** [siddontang/go-mysql#452]
我看源码里面是有只关心指定表的配置,但是没有实现.所有的数据表都会解析,如果有大量的binlog,但是只关心少量的表,每次解析一次RowsEvent后发现不是我们关心的表又进行下一次操作,就会把cpu拉的很高(从很早的binlog开始解析),如果要做监听指定表的话,应该以怎样的方式最好呢?

**Comment by always-waiting** [comment]
有参数可以配置include_table_regex

**Comment by wule61** [comment]
> 有参数可以配置include_table_regex

我试试看
