### ISSUE TITLE
关于client链接问题

### ISSUE THREAD

**Issue by always-waiting** [siddontang/go-mysql#457]
```
		if this.DBClient, err = client.Connect(
			ruleCfg.MasterDBCfg.Addr,
			ruleCfg.MasterDBCfg.User,
			ruleCfg.MasterDBCfg.Passwd,
			ruleCfg.MasterDBCfg.Db,
		); err != nil {
			return
		}

```

问一下，这样做一个mysql的链接，会有自动关闭的情况吗？
我需要的问题是: 在闲置了一段时间后，调用this.DBClient.Execute(...) 函数时报　如下错误:
```
Write failed. err write tcp 127.0.0.1:25818->127.0.0.1:3358: write: broken pipe: connection was bad
```
请问我要怎么解决？

**Comment by always-waiting** [comment]
@siddontang 
这个问题请帮忙看看，我能够设置链接永不关闭吗？
因为同步时需要反查数据库

**Comment by always-waiting** [comment]
@siddontang 
还是我需要自己写一个断线重连功能?

**Comment by always-waiting** [comment]
@siddontang 
可以确认是由于链接空闲过长导致了这个问题，目前client有没有重连的功能?我看文档里没有写

**Comment by always-waiting** [comment]
@siddontang 
还有一个问题，我有一个正在运行的go程序，如何给这个程序传递参数让其执行一些操作。

例如主程序起了20个子任务，每个任务有一个名字，希望给主程序传递参数(restart subtask1)，让subtask1子任务重启，而不影响其他子任务。

**Comment by always-waiting** [comment]
具体的应用场景是这样的：
有一个主库，目前对主库的同步有7个规则，比如一个是日志，一个是同步给另一个库，一个是给es等等。
每一个规则是一个子任务。如果某一个规则需要重启，总不希望把整个程序都重启了。
@siddontang

**Comment by siddontang** [comment]
连接不关闭，两种方式：

1. 在 MySQL 那边调整下 read/write timeout 配置
2. 在 client 这边写个 tick，定期调用 ping

**Comment by always-waiting** [comment]
@siddontang 
谢谢~~
使用了定期ping的方式，同时加了一个判断，如果执行失败，会检查一下是否因为链接断开。
