### ISSUE TITLE
canal运行的时候出现panic，数组越界，帮忙看下

### ISSUE THREAD

**Issue by liuhuanqiang** [siddontang/go-mysql#458]
[2019/12/17 18:02:51] [info] sync.go:235 table structure changed, clear table cache: company.user_membership_copy
2019-12-17 18:02:51 DEBUG /Users/liuhuanqiang/gowork/src/base_architect/canal_center/src/canalcenter/server/canal.go:103 OnTableChanged scheduled, database name:company, table name:user_membership_copy
panic: runtime error: index out of range [2] with length 2

goroutine 55 [running]:
github.com/siddontang/go-mysql/canal.(*RowsEvent).handleUnsigned(0xc00980a440)
	/Users/liuhuanqiang/gowork/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191207160406-08dd4b57abf8/canal/rows.go:56 +0x658
github.com/siddontang/go-mysql/canal.newRowsEvent(0xc008b87400, 0x1bf3f8c, 0x6, 0xc009765830, 0x1, 0x2, 0xc0097e6ca0, 0x0)
	/Users/liuhuanqiang/gowork/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191207160406-08dd4b57abf8/canal/rows.go:39 +0xa5
github.com/siddontang/go-mysql/canal.(*Canal).handleRowsEvent(0xc0007880e0, 0xc009765890, 0x10, 0xc01b624fd0)
	/Users/liuhuanqiang/gowork/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191207160406-08dd4b57abf8/canal/sync.go:272 +0x173
github.com/siddontang/go-mysql/canal.(*Canal).runSyncBinlog(0xc0007880e0, 0x0, 0x0)
	/Users/liuhuanqiang/gowork/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191207160406-08dd4b57abf8/canal/sync.go:103 +0xbea
github.com/siddontang/go-mysql/canal.(*Canal).run(0xc0007880e0, 0x0, 0x0)
	/Users/liuhuanqiang/gowork/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191207160406-08dd4b57abf8/canal/canal.go:230 +0xdc
github.com/siddontang/go-mysql/canal.(*Canal).Run(...)
	/Users/liuhuanqiang/gowork/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191207160406-08dd4b57abf8/canal/canal.go:185
github.com/siddontang/go-mysql/canal.(*Canal).RunFrom(0xc0007880e0, 0xc0001ac1a0, 0x10, 0x1af22cdc, 0x2, 0x0)
	/Users/liuhuanqiang/gowork/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191207160406-08dd4b57abf8/canal/canal.go:192 +0x59
canalcenter/server.Instance.StartInstance(0xc0007880e0, 0xc0000b24e0, 0x1da4c40, 0xc00000ed00, 0xc0001737c4, 0x5, 0xc0001737d0, 0xe, 0x2421fd2, 0x1)
	/Users/liuhuanqiang/gowork/src/base_architect/canal_center/src/canalcenter/server/instance.go:78 +0x143
created by main.main
	/Users/liuhuanqiang/gowork/src/base_architect/canal_center/src/canalcenter/main.go:38 +0x31c

**Comment by siddontang** [comment]
能否给下出问题的 binlog？或者最小化复现的 case？

**Comment by liuhuanqiang** [comment]
> 能否给下出问题的 binlog？或者最小化复现的 case？

看了下是因为表结构变更之后 ，新插入的数据会出现这种问题 ，我已经改掉了代码

**Comment by fenghuilee** [comment]
怎么解决的
