### ISSUE TITLE
invalid table id %d, no correspond table map event

### ISSUE THREAD

**Issue by zhapuyu** [siddontang/go-mysql#48]
As TableMapEvent and WriteRowsEventV2 are non-atomic, how can program work when TableMapEvent is processed but program restart, which makes goroutine named "onStream()" exit?

**Comment by siddontang** [comment]
Hi @zhapuyu 

If we have processed TableMapEvent and then restart, the following event may miss the table id when we sync from last saved position. 

I have no way to fix it now, maybe we can not save position for TableMapEvent?

**Comment by zhapuyu** [comment]
yes .  That's a suitable way to fix the problem. 
https://github.com/siddontang/go-mysql/pull/49 . Please.
