### ISSUE TITLE
Unknown table 'COLUMN_STATISTICS' in information_schema

### ISSUE THREAD

**Issue by letian0805** [siddontang/go-mysql#538]
###  bug
failed with mysqld version 5.7, mysqldump version 8.0
success with mysql version 8.0, mysqldump  version 8.0

### error log
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'test' AND TABLE_NAME = 'testa';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)

**Comment by pparshin** [comment]
It is not a bug, you should pass the option `--column-statistics=0` to mysqldump. It is the new option added to the mysqldump >= 8.0

**Comment by letian0805** [comment]
Thanks
