### ISSUE TITLE
Canal output file `master.info` will lost binlog file name.

### ISSUE THREAD

**Issue by toontong** [siddontang/go-mysql#81]
![image](https://cloud.githubusercontent.com/assets/416141/19267928/14938de6-8fe4-11e6-9945-24dbebd8631d.png)

full bin_name was 'mysqld-bin.001957'

**Comment by siddontang** [comment]
Do you update the newest code?

**Comment by toontong** [comment]
Yes

**Comment by siddontang** [comment]
What's your git commit? I have already fixed this in https://github.com/siddontang/go-mysql/pull/75
