### ISSUE TITLE
support DATETIME subsecond fraction in row_event

### ISSUE THREAD

**Issue by shlomi-noach** [siddontang/go-mysql#89]
As per https://github.com/siddontang/go-mysql/blob/e1dd629909a09927b9d237cf91831ad82ae39146/replication/row_event.go#L658-L659, the `replication` library ignores the `DATETIME` fractional value. I'm wondering what is the reason for that, and whether this should not be supported.

Related: https://github.com/github/gh-ost/issues/300

**Comment by shlomi-noach** [comment]
@siddontang See possible solution downstream: https://github.com/github/go-mysql/pull/3

**Comment by siddontang** [comment]
Hi @shlomi-noach 
Can you send me a PR?

**Comment by shlomi-noach** [comment]
addressed by https://github.com/siddontang/go-mysql/pull/90
